package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'LavalinkKt_build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("LavalinkKt_build")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "lavalinkktVcsRoot"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = storedToken {
                        tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:f377899c-08d9-45ed-8816-a3ef0077239e"
                    }
                }
            }
        }
        feature1.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = storedToken {
                    tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:0224f02c-a618-4782-8239-75364ab55f97"
                }
            }
        }
    }
}
