package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'kord'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id("kord")
    name = "kord"

    params {
        password("env.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword", "credentialsJSON:52929ed0-01b0-4025-85d9-5bf69c42cb79", display = ParameterDisplay.HIDDEN, readOnly = true)
        password("env.ORG_GRADLE_PROJECT_mavenCentralPassword", "credentialsJSON:56a86492-6c2d-4ed4-8121-6fdec2cb1155", display = ParameterDisplay.HIDDEN, readOnly = true)
        password("env.ORG_GRADLE_PROJECT_mavenCentralUsername", "credentialsJSON:732f0780-6752-42bc-a222-48c171a06b19", display = ParameterDisplay.HIDDEN, readOnly = true)
        password("env.ORG_GRADLE_PROJECT_signingInMemoryKey", "credentialsJSON:ddba5b0d-4fc1-4e83-b94f-748c53b0f1e0", display = ParameterDisplay.HIDDEN, readOnly = true)
    }

    features {
        githubIssues {
            id = "PROJECT_EXT_1"
            displayName = "kordlib/kord"
            repositoryURL = "https://github.com/kordlib/kord"
            authType = storedToken {
                tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:14179102-c8b1-4427-82dc-d7ab819ae5d7"
            }
        }
    }
}))

