package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Cache_HttpsGithubComKordlibCacheRefsHeadsMaster'
in the project with id = 'Cache', and delete the patch script.
*/
create(RelativeId("Cache"), GitVcsRoot({
    id("Cache_HttpsGithubComKordlibCacheRefsHeadsMaster")
    name = "https://github.com/kordlib/cache#refs/heads/master"
    url = "https://github.com/kordlib/cache"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:57833e23-d218-4f37-ac17-55edd9393949"
    }
}))

