package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'emojiVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("emojiVcsRoot")) {
    val expected = GitVcsRoot({
        id("emojiVcsRoot")
        name = "kordlib/emoji"
        url = "https://github.com/kordlib/kordx.emoji"
        branch = "refs/heads/main"
        branchSpec = """
            |+:refs/heads/*
            |+:refs/tags/*
        """.trimIndent()
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:92aea938-40e1-421f-8926-79db8fa10b8d"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:363e801f-3ff6-46a2-af59-05ed7b5cbb56"
        }
    }

}
