package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'kordVcsRoot'
in the project with id = 'kord', and delete the patch script.
*/
create(RelativeId("kord"), GitVcsRoot({
    id("kordVcsRoot")
    name = "kordlib/kord"
    url = "https://github.com/kordlib/kord"
    branch = "refs/heads/main"
    branchSpec = """
        |+:refs/pull/*/head
        |+:refs/heads/*
        |+:refs/tags/*
    """.trimIndent()
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:14179102-c8b1-4427-82dc-d7ab819ae5d7"
    }
}))

