package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Lavalink_HttpsGithubComKordlibLavalinkKtRefsHeadsMain'
in the project with id = 'Lavalink', and delete the patch script.
*/
create(RelativeId("Lavalink"), GitVcsRoot({
    id("Lavalink_HttpsGithubComKordlibLavalinkKtRefsHeadsMain")
    name = "https://github.com/kordlib/Lavalink.kt#refs/heads/main"
    url = "https://github.com/kordlib/Lavalink.kt"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_ead29039499734d5f53ebb99e1e14bf5:-1:f377899c-08d9-45ed-8816-a3ef0077239e"
    }
}))

